### ISSUE TITLE
implicit declaration of function 'vips_autorot_get_angle'

### ISSUE THREAD

**Issue by perelin** [davidbyttow/govips#99]
Hi,

I´m building VIPS and govips in an Alpine container. There I get this error message:

```
# github.com/davidbyttow/govips/pkg/vips
bridge.c: In function 'autorot_get_angle':
bridge.c:37:9: warning: implicit declaration of function 'vips_autorot_get_angle'; did you mean 'autorot_get_angle'? [-Wimplicit-function-declaration]
   37 |  return vips_autorot_get_angle(img);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         autorot_get_angle
```

My Dockerfile looks like this:

```Dockerfile
FROM golang:alpine 
ARG VIPS_VERSION=8.10.0
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download
RUN apk update && apk update
RUN apk --no-cache add \
	poppler-glib \
	poppler-dev \
	build-base \
	autoconf \
	automake \
	libtool \
	pkgconf \
	glib-dev \
	expat-dev \
	jpeg-dev \
	libjpeg-turbo-dev \
	bc
RUN wget -O- ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz | tar xzC /tmp
RUN cd /tmp/vips-${VIPS_VERSION} \
	&& ./configure --prefix=/usr --disable-static --disable-debug \
	&& make V=0 \
	&& make install
RUN mkdir /build 
ADD ./ /build/
WORKDIR /build/cmd/server 
RUN go build
USER appuser
COPY /build/cmd/server/server  /app/server
WORKDIR /app
CMD ["./server"]
```

go.mod entry for govips is

```
github.com/davidbyttow/govips v0.0.0-20200802170752-18370d7d84a1 // indirect
```

Any idea how to approach this?

**Comment by perelin** [comment]
So, I fixed it for me by changeing this https://github.com/davidbyttow/govips/commit/fbf235c327404e45eb1f645ae23728ffe9a1ca90 

Don´t know if it has any side effect. Pull request?

**Comment by sgulseth** [comment]
This issue seems to be introduced in eb0d6f95da713a7ade95f88af43e5a647d850a61.

A workaround is to install the earlier version with `go get -u github.com/davidbyttow/govips@cbefdd8c639afe1400dd8d6cc71f60a2943c3e11` until master is fixed

**Comment by tonimelisma** [comment]
Hey @perelin and @sgulseth we've upgraded govips with a lot of new functionality and bug fixes. This should no longer be an issue, especially with libvips 8.10. Please comment or reopen if you still have problems.

**Comment by oogali** [comment]
@perelin @sgulseth `vips_autorot_get_angle` was deprecated in the upstream library's August 8th release:
- https://github.com/libvips/libvips/releases/tag/v8.10.0

Specifically, this commit:
- https://github.com/libvips/libvips/commit/981d5c4b1695de0e984bb1ef7472b35759b36c8d

If you're getting this error, it means you're attempting to use govips pre-2.0 and libvips v8.10.0 (or newer).
